from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ResearchLesson:
    slug: str
    title: str
    published: str
    status: str
    source_url: str
    code_url: str | None
    prerequisite: str
    why: str
    simple: str
    mental_model: str
    mechanism: str
    reported_evidence: str
    boundary: str
    practical: str
    check: str


# This is a curated reading route, not an exhaustive bibliography. The stable
# spine teaches concepts; this dated track teaches how the research changed.
RESEARCH_SNAPSHOT_DATE = "2026-08-12"

RESEARCH_LESSONS = (
    ResearchLesson(
        "read-research-without-being-fooled",
        "Read post-training research without being fooled",
        "2026-08-12",
        "course synthesis; not a research paper",
        "https://arxiv.org/",
        None,
        "Spine 05, objectives and experiments",
        "Fast-moving post-training papers often change the model, data, reward, sampling budget, and evaluation at once. A leaderboard gain can be real while the claimed cause remains uncertain. This lesson gives you an evidence contract before you read the papers that follow.",
        "Treat a paper as an argument with inspectable parts: a claim, a comparison, an intervention, observations, and limits. Your job is not to decide whether the authors are smart. Your job is to decide exactly which claim the evidence supports.",
        "A paper is like a controlled repair report. If a mechanic changes the engine, tires, fuel, and driver and the lap becomes faster, the car is faster under that configuration. The report has not isolated which change caused the gain. The analogy stops because ML experiments also sample stochastic training and evaluation processes.",
        "Extract six objects: the base checkpoint; train data and contamination controls; algorithm and resolved configuration; reward or preference source; evaluation protocol including sampling budget; and comparator. Then mark each result as reported, reproduced, or independently measured. Check whether the ablation removes one causal ingredient at a time, whether seeds expose variance, and whether pass@1, pass@k, best-of-N, and token budgets are matched. Record publication status and paper version because a preprint may change.",
        "The lessons in this track report only what the cited primary source claims. The repository does not reproduce their GPU runs. Where a paper supplies code, that improves inspectability but does not prove the published result on this machine.",
        "A paper can demonstrate a result on named models and benchmarks without establishing a universal law, a production safety claim, or an isolated causal mechanism. Absence of a baseline is missing evidence, not evidence that the baseline loses.",
        "Pick one result table from any later lesson. Write a claim ledger with columns for claim, direct evidence, alternative explanation, missing control, and the smallest reproduction that could falsify the claim. Check the exact arXiv version and publication status on the day you read it.",
        "Can you state a paper's strongest supported claim without repeating its title or upgrading correlation into causation?",
    ),
    ResearchLesson(
        "lora",
        "LoRA: learn a low-rank weight update instead of every weight",
        "2021",
        "ICLR 2022 conference paper",
        "https://arxiv.org/abs/2106.09685",
        "https://github.com/microsoft/LoRA",
        "Spine 02, matrices, and Spine 09, LoRA",
        "LoRA changed the economics and artifact shape of model adaptation. Instead of storing a complete new copy of every trained weight, it freezes the base model and learns small low-rank matrices inside selected layers.",
        "A large weight matrix stays fixed. Training learns two thin matrices whose product is added to it. If the useful task update lies near a low-dimensional subspace, far fewer trainable numbers can approximate it.",
        "Rather than replacing an entire wall, install a small adjustable frame that changes how forces pass through it. The frame still depends on the exact wall, and a narrow frame cannot express every possible reconstruction.",
        "For a base weight W with input width d and output width k, LoRA uses W plus a scaled product B*A where A and B have rank r much smaller than d or k. The base receives no gradient update; optimizer state is needed only for adapter parameters. Placement, rank, scaling, initialization, dropout, target modules, and whether adapters are merged at deployment remain explicit choices. The paper studies transformer adaptation across language tasks and analyzes update rank.",
        "The paper reports matching or exceeding full fine-tuning on several tested models and tasks while training dramatically fewer parameters and avoiding additional inference latency when the update is merged. Read the exact model/task tables before reusing those comparisons.",
        "Fewer trainable parameters do not imply the same reduction in activations, forward compute, wall-clock time, or total GPU memory. Low rank is an inductive bias, not proof that every task update is low rank. An adapter is tied to its base-model identity.",
        "For a 4096-by-4096 weight, compute dense update entries and rank-8 LoRA entries. Then create a memory ledger separating frozen weights, trainable adapters, gradients, optimizer states, activations, and temporary buffers. State which categories LoRA directly changes.",
        "Why can LoRA cut optimizer-state memory sharply while a long sequence still causes an out-of-memory failure?",
    ),
    ResearchLesson(
        "qlora",
        "QLoRA: quantize the frozen base while training adapters",
        "2023",
        "NeurIPS 2023 paper",
        "https://arxiv.org/abs/2305.14314",
        "https://github.com/artidoro/qlora",
        "LoRA lesson and Spine 09",
        "QLoRA made useful fine-tuning experiments possible on much smaller hardware by combining a frozen 4-bit base representation with trainable LoRA adapters and memory controls.",
        "Store the large frozen reference weights compactly, dequantize them as needed for computation, and send gradients into the small adapter weights rather than the quantized base. The model is quantized for storage during training; the learned update is not simply four-bit gradient descent on every parameter.",
        "Keep a compressed encyclopedia on the desk and write corrections in a small notebook. You consult the encyclopedia during every answer, so compression saves shelf space but does not remove reading work or notebook quality requirements.",
        "The paper introduces 4-bit NormalFloat for normally distributed weights, double quantization of quantization constants, and paged optimizers for memory spikes, combined with LoRA. Gradients pass through operations involving the dequantized frozen weights into adapters. The work trains a large set of models across sizes and instruction datasets and evaluates chatbot behavior with automated and human comparisons.",
        "The paper reports fine-tuning a 65B model on one 48GB GPU in its setup while preserving the tested full-precision fine-tuning performance, and reports Guanaco evaluation results. It also reports that common chatbot benchmarks and automated judges have reliability limitations.",
        "A model fitting in memory does not mean it trains quickly, that its kernel path is efficient on every GPU, or that four-bit deployment is implied. 'Preserving performance' is bounded to tested tasks and configurations. Quantization errors, adapter rank, and compute dtype can interact.",
        "Given a hypothetical 7B-parameter base, derive only the raw 16-bit-versus-4-bit weight storage ratio, then explicitly list everything that estimate omits. Design a QLoRA-versus-LoRA comparison with matched data, updates, sequence length, and evaluation.",
        "Which weights receive optimizer updates in QLoRA, and why is that different from quantization-aware full-parameter training?",
    ),
    ResearchLesson(
        "reinforce-and-rloo",
        "From REINFORCE to RLOO: the simple policy-gradient line",
        "1992; RLOO paper 2024",
        "REINFORCE: journal paper; RLOO: ACL 2024 paper",
        "https://aclanthology.org/2024.acl-long.662/",
        "https://github.com/huggingface/trl/blob/main/trl/trainer/rloo_trainer.py",
        "Spine 13, policy gradients",
        "REINFORCE is the small equation underneath much modern language-model RL. The 2024 RLOO study is important because it asks whether language-model feedback tasks need PPO's learned critic and complexity at all.",
        "Sample several answers to the same prompt. Score them. For each answer, compare its score with the average score of the other answers. Increase the probability of above-peer answers and decrease the probability of below-peer answers.",
        "Imagine four runners on the same course and day. Each runner's baseline is the other three runners, not a separate coach predicting an absolute time. This controls some prompt difficulty. It fails when every runner gets the same score or when the small group is unrepresentative.",
        "REINFORCE weights a sampled sequence log-probability by return minus a baseline. RLOO samples k responses per prompt and gives response i a leave-one-out advantage: its reward minus the mean reward of the other k-1 responses. The baseline does not depend on response i, preserving the policy-gradient expectation under the stated sampling assumptions. The method can retain a reference-policy KL term while deleting PPO's learned value model, generalized advantage estimation, and value loss.",
        "The ACL 2024 paper reports that REINFORCE-style methods, particularly RLOO, can match or outperform PPO and some direct-alignment methods on its tested RLHF setups while using a simpler loop. Read its tasks, judge, model scales, and compute accounting before carrying that conclusion elsewhere.",
        "RLOO does not eliminate online sampling, reward misspecification, reference-model memory, or variance. A result on preference rewards does not establish the same ranking for sparse multi-step agent environments.",
        "Using rewards [0, 1, 1, 0.5], compute each leave-one-out baseline and advantage. Compare them with this repository's group mean and standard-deviation advantages. Then specify a matched RLOO-versus-GRPO experiment with identical prompts, samples, rewards, tokens, and update budget.",
        "Why is the leave-one-out baseline less biased than subtracting a baseline that includes the current sample's own reward?",
    ),
    ResearchLesson(
        "ppo",
        "PPO: the general-purpose optimizer that entered RLHF",
        "2017",
        "arXiv technical paper; widely used algorithm",
        "https://arxiv.org/abs/1707.06347",
        "https://github.com/openai/baselines",
        "Spine 14, PPO and KL control",
        "PPO became a central reference point because it offered a practical compromise between one tiny on-policy update and a difficult trust-region optimization. Later post-training work is often best understood as retaining, deleting, or changing one PPO component.",
        "PPO asks: how can we learn more than once from fresh experience without letting the new policy become so different that the experience stops describing it? Its clipped surrogate limits the reward for pushing a sampled action's probability ratio too far.",
        "A receipt from yesterday can guide today's purchase only while prices stay similar. Reusing it after prices change radically is misleading. The probability ratio measures that local change for sampled actions; the clip stops paying for some excessive movement but is not a global safety fence.",
        "Collect trajectories with an old policy, save old action log-probabilities, estimate advantages with returns and often a value function, then optimize minibatches for multiple epochs. The objective uses the minimum of the unclipped ratio-times-advantage and a clipped version. The original paper evaluates continuous-control and Atari environments. RLHF systems later add sequence modeling, learned rewards, reference-policy KL penalties, and distributed rollouts—those are adaptations, not all properties of the 2017 paper.",
        "The paper reports competitive performance and simpler implementation than trust-region policy optimization across its tested environments. It does not contain modern LLM experiments; its importance to this course is algorithmic lineage.",
        "Clipping a sampled-action ratio does not bound every distributional change, guarantee monotonic improvement, or solve reward hacking. PPO results depend on implementation details, advantage normalization, minibatching, value fitting, and sample freshness.",
        "Run `pt101 ppo` and enumerate all four sign-and-ratio cases. Then draw the state kept by a real learner: policy, old log-probabilities, rewards, advantages, reference log-probabilities, value targets, masks, and checkpoint IDs. Mark which identities must match.",
        "Which parts of an LLM PPO stack come from the original PPO algorithm, and which come from the RLHF application?",
    ),
    ResearchLesson(
        "instructgpt",
        "InstructGPT: demonstrations, preferences, reward model, and PPO",
        "2022",
        "NeurIPS 2022 paper",
        "https://arxiv.org/abs/2203.02155",
        None,
        "Spine 08 through 14",
        "InstructGPT is the clearest influential end-to-end RLHF system paper: it connects labeler demonstrations, pairwise rankings, a learned reward model, PPO, and human evaluation into one pipeline. It also shows why parameter count and instruction-following quality are different axes.",
        "First show the model examples of desired answers. Then ask humans which sampled answers are better. Train a judge from those comparisons. Finally let the model generate answers and update it toward higher judge scores while constraining drift.",
        "It resembles teaching, exams, and coaching, but the learned reward model is not a human conscience. It is a statistical proxy trained on a bounded comparison distribution and can be exploited outside that distribution.",
        "The paper starts with supervised fine-tuning on demonstrations, trains a reward model with a Bradley–Terry-style pairwise loss, and optimizes the policy using PPO against reward minus a KL-related constraint. It also mixes a pretraining objective in one variant to reduce capability regressions. Evaluation includes labeler preferences and public NLP datasets, with labeler screening and held-out customer prompts described in the paper.",
        "The paper reports that its 1.3B InstructGPT model was preferred to 175B GPT-3 on its human evaluation distribution, alongside improvements in truthfulness and toxicity measures and some remaining mistakes. That is a reported result under the paper's models, raters, prompts, and 2022 evaluation protocol.",
        "It does not prove all smaller aligned models outperform larger base models, that reward models capture human values, or that the pipeline removes harmful behavior. The authors explicitly discuss residual failures and alignment limitations.",
        "Draw the complete data lineage: raw prompt, demonstration, SFT checkpoint, sampled candidates, comparison, reward-model checkpoint, PPO trajectory, candidate, held-out human evaluation. For every arrow write the identity and artifact needed to reproduce it.",
        "Why is evaluation by fresh held-out labelers stronger evidence than reporting only the reward model's score after PPO?",
    ),
    ResearchLesson(
        "constitutional-ai",
        "Constitutional AI: principles, self-revision, and AI feedback",
        "2022",
        "arXiv research paper",
        "https://arxiv.org/abs/2212.08073",
        None,
        "InstructGPT lesson and Spine 16",
        "Constitutional AI is a foundational RLAIF recipe. It explores how written principles and model-generated critiques/preferences can reduce the amount of direct human harmlessness labeling while keeping human oversight at the level of selecting the constitution and evaluating results.",
        "Give a model a set of principles. Have it critique and revise problematic answers using those principles. Then use AI-generated preference comparisons to train a preference model and optimize an assistant.",
        "A style guide lets editors apply consistent rules without asking the publisher about every sentence. The guide is still written and interpreted by people, can contain conflicts, and does not guarantee the editor spots every violation.",
        "The pipeline has a supervised self-critique-and-revision stage followed by reinforcement learning from AI feedback. A helpful-only model produces responses; a model critiques and revises them using sampled constitutional principles, creating supervised data. For the RL stage, a model compares response pairs under principles, those preferences train a preference model, and the assistant is optimized against it. The constitution, critique prompts, preference model, and human evaluation are distinct artifacts.",
        "The paper reports improved harmlessness relative to stated baselines while seeking to preserve helpfulness, and studies a less evasive assistant. Its human evaluations are the evidence for behavior; AI preference agreement alone would be circular.",
        "AI feedback does not remove human values, bias, or oversight—it relocates them into principles, prompts, base models, and evaluation. A written constitution is incomplete, and the policy or feedback model may exploit its surface form.",
        "Write five concrete principles for one narrow support task, including a precedence rule for conflicts. Produce one unsafe response, a principle-linked critique, and a revision. Then write an adversarial response that follows the wording while violating the intent.",
        "Where do human decisions enter an RLAIF system even when humans label no individual training comparison?",
    ),
    ResearchLesson(
        "process-supervision",
        "Let's Verify Step by Step: outcome versus process supervision",
        "2023",
        "arXiv research paper; PRM800K data released",
        "https://arxiv.org/abs/2305.20050",
        "https://github.com/openai/prm800k",
        "Spine 11 and 16, reward models and verifiable feedback",
        "A final-answer reward cannot tell which intermediate step first went wrong. This paper made process reward models and step-level feedback concrete at scale for mathematical reasoning.",
        "Outcome supervision grades only the final answer. Process supervision marks each reasoning step. The second signal is denser and can identify a plausible-looking path that arrives at the right answer for the wrong reason.",
        "Checking only a destination is like grading a navigation route by whether the driver arrived. Step checks inspect each turn. But a step grader can still miss a hidden shortcut or penalize an unconventional valid route.",
        "The work collects human labels on intermediate steps and trains process-supervised reward models, then compares them with outcome-supervised reward models on MATH problems. It also uses active learning to spend labels on useful examples. A process reward can rank candidate solutions by aggregating step assessments. This is reward modeling and selection evidence; do not silently translate it into a claim about a particular online RL algorithm.",
        "The paper reports that process supervision outperformed outcome supervision in its setting and that its best process-supervised model solved 78 percent of a representative MATH test subset. PRM800K contains the released step-level labels.",
        "The result is domain- and protocol-specific. Human step labels are expensive and can disagree. A written chain of thought is not guaranteed to be a faithful causal trace of the model's internal computation, and a process verifier can itself be gamed.",
        "Take three short arithmetic solutions: correct path/correct answer, wrong path/correct answer, and correct prefix/wrong final step. Build outcome and step label tables. Show which pairs outcome supervision cannot distinguish. Write a policy for ambiguous but valid alternative steps.",
        "When is a process label actually more informative than a trusted executable outcome checker, and when does it merely add another proxy?",
    ),
    ResearchLesson(
        "dpo",
        "DPO: turn preference optimization into a classification loss",
        "2023",
        "NeurIPS 2023 paper",
        "https://arxiv.org/abs/2305.18290",
        "https://github.com/eric-mitchell/direct-preference-optimization",
        "Spine 15, Direct Preference Optimization",
        "DPO changed the operational shape of preference optimization. Under its stated KL-regularized reward model, it derives a policy objective that uses preference pairs and a reference model without fitting an explicit reward model or running online PPO.",
        "For each chosen and rejected answer, ask whether the trainable policy prefers the chosen answer more strongly than the frozen reference does. Increase that relative margin.",
        "A before-and-after comparison is the right analogy: the reference says how much the starting system preferred A over B; DPO rewards the candidate for moving that odds ratio toward the labeled winner. It does not discover new pairs while training.",
        "Compute sequence log-probabilities for chosen and rejected answers under policy and reference. Form the difference of their log-probability gaps, scale it by beta, and minimize a negative log-sigmoid loss. The derivation connects the optimal policy of a particular KL-constrained reward objective to an implicit reward parameterization. In practice, tokenization, prompt masking, length, beta convention, reference identity, and pair construction materially affect results.",
        "The paper reports competitive or stronger results than its PPO-based RLHF baselines on sentiment control, summarization, and dialogue while using a simpler training pipeline in the tested settings.",
        "DPO is offline preference optimization, not an interactive RL loop. Its comparisons may be stale for the updated policy. Later work finds settings where online PPO performs better, so 'DPO replaces PPO' is too broad.",
        "Run `pt101 dpo`, derive its scalar gradient, and reverse the pair. Then design an experiment comparing DPO with continued SFT and PPO using matched base model, prompts, evaluation, and total generated tokens. State how you will handle answer length.",
        "What coverage failure can no amount of DPO optimization repair if the relevant behavior never appears in the fixed preference pairs?",
    ),
    ResearchLesson(
        "kto",
        "KTO: learn from desirable and undesirable examples without pairs",
        "2024",
        "ICML 2024 conference paper",
        "https://arxiv.org/abs/2402.01306",
        "https://github.com/ContextualAI/HALOs",
        "DPO lesson",
        "DPO requires a chosen and rejected response for the same prompt. KTO is important when feedback arrives as independent thumbs-up or thumbs-down examples and natural pairs are expensive or artificial.",
        "Instead of asking which of two answers wins, label each observed answer as desirable or undesirable. Compare its policy-versus-reference likelihood signal with a distribution-level reference point and optimize a loss shaped by different attitudes toward gains and losses.",
        "A user can say 'this trip was bad' without taking the same trip with a second driver for comparison. The missing counterfactual makes learning harder, and the interpretation depends on what counts as an ordinary outcome.",
        "The paper frames several alignment objectives as human-aware losses and draws on prospect-theoretic utility. KTO uses binary desirability labels, a reference policy, and a KL-related reference point. Desirable and undesirable examples can receive separately weighted loss terms, which matters when feedback classes are imbalanced. The method is offline and inherits the coverage and policy-shift limits of its fixed data.",
        "The paper reports matching or exceeding preference-pair methods on tested model scales from 1B to 30B while learning from unary desirable/undesirable signals. It also argues that no one human-aware loss is universally superior.",
        "Prospect theory is a modeling inspiration, not proof that the loss captures actual human psychology in deployment. Unary labels can hide which alternative would be better and are sensitive to class balance, source policy, and labeling threshold.",
        "Convert a four-pair preference dataset into eight unary labels, then remove one member from half the pairs. State what KTO can still use and what relational information is lost. Design a class-imbalance stress test.",
        "When is a cheap unary signal worth the loss of within-prompt comparative information?",
    ),
    ResearchLesson(
        "simpo",
        "SimPO: reference-free preference optimization with a length-normalized reward",
        "2024",
        "NeurIPS 2024 conference paper",
        "https://papers.nips.cc/paper_files/paper/2024/hash/e099c1c9699814af0be873a175361713-Abstract-Conference.html",
        "https://github.com/princeton-nlp/SimPO",
        "DPO and KTO lessons",
        "SimPO tests whether offline preference optimization needs a separate frozen reference model. It replaces DPO's policy-versus-reference implicit reward with the policy's average response log-probability and adds a target margin.",
        "Raise the chosen response's average per-token log-probability above the rejected response's by at least a desired gap. Averaging addresses raw sequence-length accumulation, and dropping the reference reduces memory and computation.",
        "Compare average score per question rather than total points when exams have different lengths. This reduces one length effect but does not prove verbosity, brevity, or content quality is fully controlled.",
        "For each preference pair, SimPO computes average log-probability per response under the trainable policy, takes the chosen-minus-rejected difference, subtracts a target reward margin, and applies a Bradley–Terry-style log-sigmoid loss. There is no reference-policy forward pass. The margin asks the policy to separate responses rather than merely order them. Data source and offline coverage remain unchanged.",
        "The NeurIPS 2024 paper reports improvements over DPO and tested variants on AlpacaEval 2, MT-Bench, Arena-Hard, and a real-user leaderboard comparison under its model and training setups, while reporting limited length exploitation in those evaluations.",
        "Reference-free does not mean unconstrained, safe, or immune to likelihood over-optimization. Judge-based chat benchmarks can favor style. Average token log-probability introduces its own length and tokenization behavior.",
        "For a two-token chosen response and four-token rejected response, compute total and average log-probability gaps. Add a target margin and evaluate whether the loss is satisfied. Then compare memory ledgers for DPO and SimPO.",
        "What behavior was controlled by DPO's reference model that must now be detected by external regression evaluation in SimPO?",
    ),
    ResearchLesson(
        "deepseekmath-and-grpo",
        "DeepSeekMath: GRPO and verifiable mathematical rewards",
        "2024",
        "arXiv technical report",
        "https://arxiv.org/abs/2402.03300",
        "https://github.com/deepseek-ai/DeepSeek-Math",
        "Spine 16 and 17, verifiable rewards and GRPO",
        "DeepSeekMath introduced Group Relative Policy Optimization in a complete math-model recipe. It is the bridge between general RLHF and the later wave of reasoning models trained from executable or exact rewards.",
        "Sample a group of answers to one problem. Use the group's rewards to decide which samples were better than their peers. Update the policy without training a separate value network.",
        "A classroom curve supplies a local baseline for one exam. It saves a separate predictor of expected grades, but it yields no ranking when everyone ties and it can be distorted by a tiny or mismatched group.",
        "GRPO samples multiple outputs for each question, normalizes rewards within the group to estimate advantages, and optimizes a PPO-like clipped objective with a KL term in the paper's formulation. DeepSeekMath combines this with continued pretraining on math-related data and supervised fine-tuning. The components must be separated when attributing results: the model is not evidence for GRPO alone.",
        "The report gives DeepSeekMath model results across mathematical benchmarks and introduces GRPO as a memory-reducing alternative to PPO's critic. The exact benchmark numbers are reported evidence tied to its data, model, sampling, and evaluation settings.",
        "Removing a critic does not remove multiple rollout samples, reference computation, reward design, or distributed synchronization. Group normalization can erase signal in constant-reward groups and later research identifies length-related biases in common implementations.",
        "Run `pt101 grpo` with mixed and equal rewards. Compute mean, standard deviation, and advantages. Then write an ablation matrix separating continued pretraining, SFT, reward choice, GRPO, sampling count, and test-time voting.",
        "Why can a paper prove that a full recipe works while leaving the marginal contribution of one algorithm uncertain?",
    ),
    ResearchLesson(
        "tulu-3",
        "Tulu 3: an open post-training pipeline, not one magic loss",
        "2024",
        "arXiv technical report; open artifacts",
        "https://arxiv.org/abs/2411.15124",
        "https://github.com/allenai/open-instruct",
        "Spine 05 through 21",
        "Tulu 3 matters because it treats post-training as a reproducible system: data curation, SFT, preference optimization, RL with verifiable rewards, decontamination, development evaluation, unseen evaluation, and released recipes.",
        "The lesson is not that one loss won. The lesson is that a strong model is assembled through staged data and evaluation decisions, and failed methods are useful evidence when the comparisons are controlled.",
        "A restaurant is not explained by its oven alone. Ingredients, preparation order, quality checks, and service all affect the meal. Likewise, a trainer name cannot summarize a post-training pipeline.",
        "The report builds on Llama 3.1 base models and uses SFT, DPO, and a method called RLVR. It emphasizes multi-task development and unseen evaluations, benchmark decontamination, dataset mixing, and open release of data, code, model weights, and configurations. Inspect the exact recipe for each checkpoint rather than assuming every Tulu 3 model passed through identical stages.",
        "The paper reports strong results for its open post-trained models relative to named open and closed comparators and discusses methods that did not reliably help. Its unusually broad artifact release makes it a useful reproduction target.",
        "A complete open recipe still does not make its aggregate score a universal measure, guarantee uncontaminated data, or prove every stage is necessary. Closed-model comparisons can drift as APIs change.",
        "Choose one Tulu 3 checkpoint and produce an artifact graph from base revision to final evaluation. Mark every dataset, code revision, stage, and evaluator. Then propose a tiny reproduction that keeps the stage order but reduces model and data scale, and state which claims it cannot test.",
        "Why is unseen evaluation after development tuning different from merely adding more benchmark rows to one reported average?",
    ),
    ResearchLesson(
        "deepseek-r1",
        "DeepSeek-R1: pure RL experiment versus the production recipe",
        "2025",
        "arXiv technical report; open model artifacts",
        "https://arxiv.org/abs/2501.12948",
        "https://github.com/deepseek-ai/DeepSeek-R1",
        "DeepSeekMath lesson and Spine 16",
        "DeepSeek-R1 made large-scale RL for reasoning visible, but its most important teaching distinction is between R1-Zero and R1. R1-Zero tests RL without an SFT warm-up; R1 uses cold-start data and multiple stages to improve readability, language consistency, and overall behavior.",
        "R1-Zero asks whether verifiable reward can amplify reasoning behavior from a base model. R1 asks how to turn that experiment into a more usable model through curated starts, RL, rejection sampling, supervised training, and additional alignment.",
        "Letting a student discover a solution style from exam scores tests exploration. Giving a small set of worked formats first makes the writing usable. The analogy does not show what reasoning was already latent in pretraining.",
        "The report applies large-scale RL with rule-based accuracy and format rewards to DeepSeek-V3-Base for R1-Zero. The R1 pipeline adds cold-start supervised data, reasoning-oriented RL, rejection sampling and SFT, and another RL phase spanning helpfulness and harmlessness. It also distills reasoning outputs into smaller Qwen- and Llama-based dense models. These are distinct interventions and checkpoints.",
        "The paper reports reasoning benchmark results for R1-Zero, R1, and distilled models, plus observed behaviors such as longer reasoning and self-reflection. It also reports R1-Zero problems including readability and language mixing.",
        "An observed 'aha moment' is not proof that RL created a capability absent from pretraining. Benchmark comparison does not isolate training compute, data, base-model strength, or test-time token budget. Distillation results are not direct RL results for the student models.",
        "Create a table with rows R1-Zero, R1, and distilled student and columns base model, SFT before RL, reward, later SFT, direct RL weight update, and reported limitation. This prevents collapsing three different training paths into one claim.",
        "Which DeepSeek-R1 artifact received direct RL gradients, and which artifacts learned by supervised distillation instead?",
    ),
    ResearchLesson(
        "kimi-k1-5",
        "Kimi k1.5: long-context RL and long-to-short transfer",
        "2025",
        "arXiv technical report",
        "https://arxiv.org/abs/2501.12599",
        None,
        "DeepSeek-R1 lesson and Spine 19",
        "Kimi k1.5 broadens the reasoning-RL picture beyond one algorithm. It emphasizes long-context rollouts, improved policy optimization, multimodal data, infrastructure, and transferring long reasoning into shorter responses.",
        "The recipe spends training compute letting the policy explore long solutions, then uses those solutions to improve a model that answers more briefly. Training-time exploration length and serving-time answer length can be separate design choices.",
        "A researcher may use a long scratchpad while discovering a proof and later write a concise solution. But a model's visible tokens are sampled outputs, not guaranteed faithful private thoughts, and shorter distillation can discard useful diversity.",
        "The report describes an RL framework without Monte Carlo tree search, a learned value function, or a process reward model. It discusses long-context scaling, rollout and policy-optimization techniques, multimodal training, partial rollout reuse, and several long-to-short approaches including model merging, shortest rejection sampling, DPO, and long-CoT-to-short-CoT SFT. Treat these as a system recipe, not one ablated variable.",
        "The paper reports strong benchmark results on mathematical, coding, and multimodal reasoning for long- and short-chain-of-thought variants. Those numbers depend on the stated evaluation and test-time setup and remain reported, not reproduced here.",
        "The report does not show that longer reasoning is always better, that tree search is unnecessary for all tasks, or that a short model internalizes the same mechanism as the long model. Infrastructure scale limits direct reproduction.",
        "For one task, define matched pass@1, pass@k, and token-budget evaluations for a long and short policy. Specify how you would distinguish accuracy gained by training from accuracy gained by sampling more tokens at test time.",
        "Why must a claimed long-to-short improvement be evaluated under a fixed output-token budget as well as ordinary benchmark settings?",
    ),
    ResearchLesson(
        "dapo",
        "DAPO: make large-scale reasoning RL trainable and inspectable",
        "2025",
        "arXiv technical report; code and data released",
        "https://arxiv.org/abs/2503.14476",
        "https://github.com/volcengine/verl/blob/main/docs/algo/dapo.md",
        "DeepSeek-R1 lesson and Spine 14 through 19",
        "DAPO is important as an engineering paper: it identifies concrete failure modes encountered while scaling reasoning RL and releases a recipe intended to make the training path reproducible.",
        "A mathematically valid optimizer can still stall when every sampled answer ties, when clipping suppresses useful changes asymmetrically, or when long answers receive accidental advantages. DAPO changes sampling and loss details to keep useful learning signal flowing.",
        "Think of a factory line with four jams. Fixing the product blueprint is insufficient; each jam needs an operational control. The analogy does not prove every control generalizes beyond the reported model and math task.",
        "DAPO names four techniques: decoupled clipping with separate lower and upper ranges; dynamic sampling that filters groups with no reward variation; token-level policy-gradient loss; and overlong-reward shaping. The system is implemented using verl and reports a Qwen2.5-32B math run. Each technique changes either which samples reach training or how their token losses and constraints are aggregated.",
        "The paper reports a score of 50 on AIME 2024 for its Qwen2.5-32B base-model recipe and provides code, processed data, and training details. Its ablations are the primary evidence for the proposed techniques.",
        "A single benchmark score does not establish general instruction following, safety, or cross-domain transfer. Dynamic filtering changes the effective training distribution. Overlong penalties can suppress valid long solutions if the budget is poorly chosen.",
        "Create four synthetic reward groups: all wrong, all correct, mixed, and one outlier. Show which dynamic sampling retains. Then compare sequence-level and token-level averaging for one short and one long response with the same advantage.",
        "How can filtering zero-variance groups improve optimizer efficiency while also hiding that the current curriculum is too easy or too hard?",
    ),
    ResearchLesson(
        "dr-grpo",
        "Dr. GRPO: find length bias before celebrating longer reasoning",
        "2025",
        "arXiv critical study; code released",
        "https://arxiv.org/abs/2503.20783",
        "https://github.com/sail-sg/understand-r1-zero",
        "GRPO and DeepSeek-R1 lessons",
        "This paper is important because it challenges two tempting stories: that reasoning behaviors necessarily emerge only during RL, and that longer outputs during GRPO necessarily mean deeper reasoning.",
        "Inspect the base model before crediting RL, and inspect the loss normalization before crediting longer thought. An optimizer can accidentally reward response length even when extra tokens belong to incorrect answers.",
        "If a race score is divided by each runner's distance in one place and by a fixed distance elsewhere, incentives can favor running farther rather than reaching the finish efficiently. The exact analogy depends on the loss normalization being studied.",
        "The authors evaluate several base models for pre-existing reasoning behaviors and analyze common GRPO normalization. They argue that sample-level and token-level normalization choices introduce an optimization bias that increases response length, especially for incorrect outputs. Dr. GRPO removes the identified normalization terms in their formulation. The paper also presents a smaller R1-Zero-style training recipe.",
        "The paper reports strong AIME 2024 performance for its 7B setup, improved token efficiency, and evidence that some apparent 'aha' behavior exists in base models before RL. These are reported findings under its prompts, models, and sampling analysis.",
        "The critique does not show that all length growth is spurious, that RL cannot discover new strategies, or that Dr. GRPO wins on all domains. Base-model sampling has finite coverage, so failure to observe a behavior is not proof of absence.",
        "Construct two responses with equal reward and advantage but lengths 10 and 100. Apply per-sequence and per-token normalization choices and inspect total gradient weight. Then design a plot splitting correct and incorrect response lengths over training.",
        "What evidence would distinguish useful additional reasoning from an optimizer-induced length artifact?",
    ),
    ResearchLesson(
        "prorl",
        "ProRL: does prolonged RL expand the reasoning boundary?",
        "2025",
        "arXiv research paper; weights released",
        "https://arxiv.org/abs/2505.24864",
        "https://huggingface.co/nvidia/Nemotron-Research-Reasoning-Qwen-1.5B",
        "DeepSeek-R1 and Dr. GRPO lessons",
        "A central dispute is whether RL teaches new reasoning strategies or only makes already-likely correct samples more common. ProRL attacks that question with longer training and pass@k comparisons against extensive base-model sampling.",
        "If the trained model solves problems that the base model still misses after many attempts, the result is harder to explain as merely choosing a previously common answer. It is evidence of an expanded sampled solution region, subject to finite-search limits.",
        "Searching a library longer can reveal a book that was always present; learning can also write a new route into the catalog. Finite base-model sampling cannot prove a route was absent, but matched large-k curves give stronger evidence than pass@1 alone.",
        "ProRL combines prolonged online RL, KL control, reference-policy resetting, and diverse tasks. It evaluates both pass@1 and pass@k, including tasks where extensive base sampling fails. Reference resetting changes which policy anchors the KL constraint over a long run. Diverse tasks aim to avoid narrow collapse and keep the reward frontier active.",
        "The paper reports that its RL models outperform base models across pass@k evaluations and solve some tested problems not reached by large base-model sample sets. It reports relationships among base competence, duration, and gains and releases model weights.",
        "Finite pass@k cannot prove mathematical absence from the base distribution. Training data or verifier leakage can create apparent novelty. The result does not settle whether all RL gains across models are capability expansion rather than distribution sharpening.",
        "Plot hypothetical pass@k curves for base and candidate at k=1, 8, 64, and 1024. Define three patterns: pure pass@1 sharpening, persistent candidate frontier, and uncertain crossing. State the sample and token matching needed for each inference.",
        "What claim remains justified if the base model eventually matches the RL model at very large k but costs 100 times more samples?",
    ),
    ResearchLesson(
        "cross-domain-generalization",
        "Breaking Barriers: RL gains often fail to cross domains",
        "2026 conference publication; first posted 2025",
        "ICLR 2026 conference paper",
        "https://openreview.net/forum?id=mvLhN0veUd",
        None,
        "Spine 05, 07, and 20",
        "This is an important negative result. Post-training can produce large gains near its training domain while improvements shrink or disappear on domains that require different reasoning patterns.",
        "Training on one kind of puzzle can teach a model to recognize that puzzle's structure without teaching a general problem-solving method. You need evaluations that cross the boundary you claim the model learned to cross.",
        "A student drilled on algebra may improve on new algebra worksheets but not geometry. That is not failure if algebra was the task; it is failure only if the claim was general mathematical reasoning.",
        "The paper uses two forms of evidence. Its observational study compares multiple open-weight reinforcement-post-trained models with their corresponding base models across seen and unseen domains. Its interventional study trains on individual domains and evaluates across multiple domains. Agreement between these approaches strengthens the distribution-specific interpretation, though neither covers every model or domain.",
        "The ICLR 2026 paper reports substantial gains on tasks similar to training data and inconsistent transfer, including gains that vanish on domains with different reasoning patterns.",
        "The paper does not show that RL never generalizes, that in-domain specialization lacks value, or that its chosen domain taxonomy captures every transferable skill. Negative transfer evidence must still be tied to exact datasets and models.",
        "Build a train-by-test matrix with at least four problem families. Freeze family-level splits before training. Report both diagonal in-domain gains and off-diagonal transfer, plus a general-capability suite. Refuse to publish one blended average that hides the matrix.",
        "What is the narrowest honest capability claim supported by an in-domain gain with zero off-domain transfer?",
    ),
    ResearchLesson(
        "easy-to-hard-curriculum",
        "Easy-to-hard curriculum RL: keep the policy in a learnable zone",
        "2026 conference publication; first posted 2025",
        "ICLR 2026 conference paper",
        "https://openreview.net/forum?id=KJvHnl3kUv",
        "https://github.com/divelab/E2H-Reasoning",
        "DAPO dynamic sampling and cross-domain lessons",
        "Sparse rewards on hard tasks can give nearly every rollout a zero, leaving no contrast for policy gradients. Easy-to-hard curriculum learning changes the prompt distribution so the policy first receives informative successes, then shifts toward the target difficulty.",
        "Practice where success is possible, then increase difficulty. Remove easy drills after they have served their purpose, or the model spends its budget repeating mastered behavior.",
        "A climbing wall needs reachable holds before the final overhang. But a curriculum can teach shortcuts specific to the easy stages, and a human difficulty label may not match the current policy's difficulty.",
        "E2H Reasoner partitions or schedules task distributions from easier to harder and fades easy tasks during training. The paper frames the process using approximate policy iteration and provides sample-complexity analysis under its assumptions. Empirically it studies small language models across multiple reasoning domains. The curriculum changes data selection; the underlying reward and policy optimizer must still be specified.",
        "The ICLR 2026 paper reports better reasoning performance than direct hard-task RL for tested 1.5B-to-3B models and finds that fading easy tasks helps prevent overfitting. It reports theoretical guarantees for its formalized setting, not arbitrary neural training.",
        "Difficulty is policy-dependent and changes during training. A static bucket can become stale. Easy-to-hard gains do not prove cross-domain transfer, and theoretical assumptions may not hold for the full LLM system.",
        "Create four prompt buckets using baseline success probability, not topic labels. At each evaluation checkpoint compute reward variance and mastery. Write a promotion rule that advances difficulty and a retirement rule that removes mastered easy prompts.",
        "Why is baseline error rate a more operational difficulty signal than a human label, and when can it still mislead?",
    ),
    ResearchLesson(
        "power-sampling",
        "Scalable Power Sampling: test distribution sharpening before training",
        "2026",
        "ICML 2026 conference paper",
        "https://openreview.net/forum?id=SVyjXhZlDe",
        None,
        "ProRL lesson and Spine 01",
        "This paper represents the strongest counterargument to broad claims that RL creates new reasoning. It asks whether sharpening the base model's existing distribution at inference time can recover similar gains without training or external rewards.",
        "Before paying to update weights, test whether a better sampling rule can make high-quality paths that already exist become easier to draw. If it can, the product gain may be real while the capability-acquisition story is too strong.",
        "A weighted die can be sharpened so its already-likely faces occur more often; no new face is created. Language sequences are harder because token choices affect future paths, so local temperature alone is not identical to a global sequence power distribution.",
        "The work starts from a power distribution over complete sequences and derives an autoregressive approximation using scaled low-temperature sampling plus a factor representing future trajectory quality. It positions the method against expensive MCMC approaches and one-shot GRPO comparisons. Because it is training-free and verifier-free, it provides a useful control for separating policy-distribution changes from newly learned task information.",
        "The ICML 2026 paper reports matching or surpassing one-shot GRPO on tested math, QA, and code tasks across four models, with much lower latency than MCMC-based power sampling.",
        "Matching one-shot GRPO does not match prolonged RL, all model scales, or all domains. A sampling algorithm can spend more inference compute or use approximations that change latency and quality. The result does not show RL is useless.",
        "For one base model, compare greedy, temperature sweep, best-of-N with a verifier, power sampling, and an RL checkpoint under equal total generated tokens and wall-clock reporting. Plot pass@1 and pass@k. Do not tune sampling on the test set.",
        "If training-free sharpening matches RL at pass@1 but RL retains a pass@k frontier, what different product and scientific conclusions follow?",
    ),
    ResearchLesson(
        "re2-resolving",
        "Re²: teach the policy to abandon a bad reasoning path",
        "2026-03-07",
        "arXiv preprint; frontier snapshot",
        "https://arxiv.org/abs/2603.07197",
        None,
        "DeepSeek-R1 and ProRL lessons",
        "Longer reasoning is not useful when the initial direction is wrong and the model keeps elaborating it. Re² studies a different behavior: explicitly restart the solution rather than always extend the current chain.",
        "When a path is clearly unproductive, begin again from the problem instead of spending every remaining token defending the first idea. The policy must learn both when to restart and how to use the fresh attempt.",
        "A maze solver can backtrack to the entrance rather than continue down a dead end. Natural-language reasoning has no perfect dead-end detector, so unnecessary restarts can waste compute or discard a nearly complete solution.",
        "The paper defines reinforcement learning with re-solving, giving the policy an opportunity or structure to abandon a prior chain and produce a new solution. It uses verifiable rewards and studies changes in redo behavior, solution direction, training-compute-matched performance, and test-time sampling. Inspect the exact prompt and trajectory construction before treating restart as an environment action.",
        "The March 2026 preprint reports increasing rare redo behavior from about 0.5 percent to above 30 percent and performance gains over its standard RLVR comparison under the paper's training-compute budget.",
        "This is a preprint, not an independently reproduced result here. More restart tokens can alter effective test-time compute. A behavior-frequency change does not by itself prove improved reasoning quality or generalization.",
        "Design a toy search task where the first branch is sometimes poisoned. Compare commit-only, backtracking, and full restart policies under the same action budget. Record success, wasted steps, false restarts, and success conditional on initial branch quality.",
        "What matched-budget measurement distinguishes useful re-solving from simply buying a second independent sample?",
    ),
    ResearchLesson(
        "agent2-rl-bench",
        "Agent² RL-Bench: can agents engineer their own post-training loop?",
        "2026-04-12",
        "arXiv preprint and Microsoft Research publication page; frontier snapshot",
        "https://arxiv.org/abs/2604.10547",
        "https://github.com/microsoft/RD-Agent/tree/main/rdagent/scenarios/rl/autorl_bench",
        "Spine 18 through 21",
        "This work moves the object of evaluation up one level. The policy being judged is an engineering agent that must design, implement, and run a post-training pipeline—not merely the model produced by one fixed trainer.",
        "Give an agent a bounded workspace, training task, grading API, and budget. Score both the improved model and the process used to reach it. Static code generation is easier than closing the loop over real training results.",
        "It resembles a lab practical where a student must run the experiment, diagnose failures, and revise the method. The driver model, scaffold, tools, and budget are part of the experimental subject.",
        "The benchmark defines six tasks across three levels, from static rule-based construction to online RL with trajectory collection. Isolated workspaces, submission instrumentation, code revisions, and post-hoc reports make the process auditable. It evaluates multiple agent systems and driver models and separates gains from SFT warm-up and online RL where possible.",
        "The April 2026 paper reports large interactive gains on some tasks and marginal gains within evaluation noise on others. It reports strong driver-model effects and finds that supervised pipelines dominate under fixed budgets in much of the benchmark, with online RL the final best route only in a subset.",
        "This is a benchmark result, not proof that autonomous agents can safely operate unrestricted training infrastructure. Task graders can be gamed, and scaffold or driver changes confound broad claims about 'the agent.'",
        "Design a levelled benchmark for this repository: level 1 selects an algorithm from a manifest, level 2 fixes a broken toy reward loop, level 3 iterates against held-out results. Log every patch, command, artifact digest, budget, and grader response.",
        "Why must an agentic post-training benchmark score the engineering trajectory and environment integrity, not only the final model metric?",
    ),
    ResearchLesson(
        "rl-with-verifiable-physics",
        "RL with Verifiable Physics: replace binary reward with graded reality",
        "2026-07-11",
        "arXiv preprint; latest dated frontier lesson in this snapshot",
        "https://arxiv.org/abs/2607.10474",
        None,
        "Spine 16 and the process-supervision lesson",
        "Many RLVR tasks reduce reward to pass or fail. Scientific and engineering tasks often contain richer error structure: two programs can execute while one is orders of magnitude more accurate. This July 2026 paper studies hybrid executable and continuous physics rewards for PDE solver generation.",
        "First reject programs that do not run. Among programs that run, score how closely the numerical solution satisfies the target physics. The policy receives more information than a single compiler bit.",
        "A bridge inspection first checks that the bridge exists, then measures deflection and stress rather than labeling every standing bridge equally correct. The simulator and discretization still approximate reality and can contain exploitable blind spots.",
        "RLVP combines hard program-validity checks with continuous rewards based on function-space accuracy and PDE-residual consistency. A single policy is trained across multiple partial-differential-equation families, and evaluation includes held-out PDEs. The reward therefore encodes both software execution and domain equations. Exact environment versions, numerical tolerances, grids, and resource limits become part of the reward contract.",
        "The July 2026 preprint reports improvements over pretrained and supervised-only baselines on its PDE benchmarks, transfer to held-out PDEs, and compositional reuse of numerical motifs. These are reported frontier findings awaiting independent reproduction here.",
        "A low residual on sampled points does not guarantee stability, convergence, physical validity under all conditions, or production solver quality. Continuous rewards can be scaled poorly, dominated by easy terms, or exploited between evaluation points.",
        "Build a tiny reward for approximating dy/dx=y with a generated Euler step: syntax validity, finite output, residual error, and held-out initial condition. Vary reward scaling and show how a large syntax bonus can drown out accuracy improvements.",
        "What independent numerical test would catch a policy that optimizes residual samples while producing an unstable solver between them?",
    ),
)
